language: android
jdk: oraclejdk8
sudo: false

android:
  components:
      # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    # The BuildTools version used by the project
    - build-tools-25.0.0
    # The SDK version used to compile the project
    - android-25
    # Additional components, otherwise bild fails to find license signature
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
    bash gradlew test --continue --stacktrace