#!/bin/bash -v
#
#  Build learnt.csv from airport diagram images
#

##+++2013-01-10
##    Copyright (C) 2013, Mike Rieker, Beverly, MA USA
##
##    This program is free software; you can redistribute it and/or modify
##    it under the terms of the GNU General Public License as published by
##    the Free Software Foundation; version 2 of the License.
##
##    This program is distributed in the hope that it will be useful,
##    but WITHOUT ANY WARRANTY; without even the implied warranty of
##    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##    GNU General Public License for more details.
##
##    EXPECT it to FAIL when someone's HeALTh or PROpeRTy is at RISk.
##
##    You should have received a copy of the GNU General Public License
##    along with this program; if not, write to the Free Software
##    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

##    Avare, open source moving map aviation GPS (support@apps4av.net)

rm -f ReadArptDgmPng_learnt.csv

time mono --debug ReadArptDgmPng.exe ReadArptDgmPng_learnpngs/AGC.png -givens \
    "1497,2141=79^56.5'W" \
    "1497,1485=79^56.0'W" \
    "1497,789=79^55.5'W" \
    "1181,211=40^21.0'N" \
    "272,211=40^21.5'N"
time mono --debug ReadArptDgmPng.exe ReadArptDgmPng_learnpngs/BED.png -givens \
    "275,207=42^28.5'N" \
    "821,207=42^28.0'N" \
    "1368,370=42^27.5'N" \
    "1446,2067=71^18.5'W" \
    "1442,1667=71^18.0'W" \
    "1446,1258=71^17.5'W" \
    "1441,859=71^17.0'W" \
    "1440,451=71^16.5'W"
time mono --debug ReadArptDgmPng.exe ReadArptDgmPng_learnpngs/BOS.png -givens \
    "1209,516=42^23'N" \
    "1205,1296=42^22'N" \
    "1206,2075=42^21'N" \
    "424,2032=71^01'W" \
    "1002,2239=71^00'W"
time mono --debug ReadArptDgmPng.exe ReadArptDgmPng_learnpngs/BVY.png -givens \
    "110,650=42^35.5'N" \
    "110,1375=42^35.0'N" \
    "110,2100=42^34.5'N" \
    "198,2012=70^55.5'W" \
    "735,2012=70^55.0'W" \
    "1270,2012=70^54.5'W"
time mono --debug ReadArptDgmPng.exe ReadArptDgmPng_learnpngs/EWB.png -givens \
    "1274,367=41^41.0'N" \
    "1272,1281=41^40.5'N" \
    "1280,2196=41^40.0'N" \
    "682,2236=70^57.5'W" \
    "1367,2234=70^57.0'W"
time mono --debug ReadArptDgmPng.exe ReadArptDgmPng_learnpngs/GUM.png -givens \
    "200,2210=144^47'E" \
    "926,2210=144^48'E"
time mono --debug ReadArptDgmPng.exe ReadArptDgmPng_learnpngs/HYA.png -givens \
    "1341,342=41^41.0'N" \
    "1082,886=41^40.5'N" \
    "1340,1431=41^40.0'N" \
    "1337,1974=41^39.5'N" \
    "199,2224=70^17.5'N" \
    "608,2225=70^17.0'N" \
    "1014,2225=70^16.5'N" \
    "1398,2229=70^16.0'N"
time mono --debug ReadArptDgmPng.exe ReadArptDgmPng_learnpngs/MVY.png -givens \
    "1372,399=41^24.0'N" \
    "1369,1299=41^23.5'N" \
    "1371,2196=41^23.0'N" \
    "458,2234=70^37.0'W" \
    "1137,2238=70^36.5'W"
time mono --debug ReadArptDgmPng.exe ReadArptDgmPng_learnpngs/NTU.png -givens \
    "274,1298=36^49'N" \
    "275,2039=36^48'N" \
    "282,555=36^50'N" \
    "1383,1719=76^01'W" \
    "789,1714=76^02'W" \
    "189,1418=76^03'W"
time mono --debug ReadArptDgmPng.exe ReadArptDgmPng_learnpngs/OWD.png -givens \
    "200,420=42^11.5'N" \
    "200,1410=42^11.0'N" \
    "284,1508=71^11.0'W" \
    "1010,1500=71^10.5'W" \
    "1742,1498=71^10.0'W"
time mono --debug ReadArptDgmPng.exe ReadArptDgmPng_learnpngs/PPG.png -givens \
    "1410,608=14^19'S" \
    "1410,1326=14^20'S" \
    "1410,2066=14^21'S"

cat ReadArptDgmPng_learnt.csv
